const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#00D4FF",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#111214",
    cardForeground: "#FFFFFF",
    primary: "#00D4FF",
    primaryForeground: "#0A0A0A",
    secondary: "#0B1929",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1D21",
    mutedForeground: "#6B7280",
    accent: "#0050FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#1F2329",
    input: "#1A1D21",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00D4FF",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#111214",
    cardForeground: "#FFFFFF",
    primary: "#00D4FF",
    primaryForeground: "#0A0A0A",
    secondary: "#0B1929",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1D21",
    mutedForeground: "#6B7280",
    accent: "#0050FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#1F2329",
    input: "#1A1D21",
  },
  radius: 12,
};

export default colors;
